name: Build Aseprite

on:
  workflow_dispatch: # allows you to manually trigger the build
  push:              # or automatically when you push code

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Skia
        run: |
          curl -L https://github.com/aseprite/skia/releases/download/m102-b85687e1af/Skia-Windows-Release-x64.zip -o skia.zip
          mkdir skia
          tar -xf skia.zip -C skia

      - name: Configure Build
        run: |
          cmake -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR=%CD%\skia ^
            -DSKIA_LIBRARY_DIR=%CD%\skia\out\Release-x64 ^
            -DSKIA_LIBRARY=%CD%\skia\out\Release-x64\skia.lib ^
            -DPNG_ARM_NEON:STRING=off

      - name: Build
        run: cmake --build build --target aseprite

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: aseprite-windows
          path: build/bin/aseprite.exe
